import { clsx, type ClassValue } from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

const twMerge = extendTailwindMerge({
  cacheSize: 1000,
  extend: {
    classGroups: {
      'font-size': [
        {
          text: [
            'heading-1',
            'heading-2',
            'heading-3',
            'heading-4',
            'heading-5',
            'heading-6',
            'tagline-1',
            'tagline-2',
            'tagline-3',
            'tagline-4',
            'tagline-5',
            'tagline-6',
          ],
        },
      ],
      'text-color': [
        {
          badge: [
            'green',
            'green-v2',
            'ns-green-light',
            'yellow',
            'yellow-v2',
            'cyan',
            'cyan-v2',
            'gray',
            'gray-light',
            'gray-dark',
            'metal',
            'white',
            'primary',
            'primary-light',
            'blur',
            'blur-v2',
            'blur-light',
            'secondary-light',
          ],

          text: [
            'primary-50',
            'primary-100',
            'primary-200',
            'primary-300',
            'primary-400',
            'primary-500',
            'primary-600',
            'primary-700',
            'primary-800',
            'secondary',
            'accent',
            'background-1',
            'background-2',
            'background-3',
            'background-4',
            'background-5',
            'background-6',
            'background-7',
            'background-8',
            'background-9',
            'background-10',
            'background-11',
            'stroke-1',
            'stroke-2',
            'stroke-3',
            'stroke-4',
            'stroke-5',
            'stroke-6',
            'stroke-7',
            'stroke-8',
            'stroke-9',
            'gradient-1',
            'gradient-2',
            'gradient-3',
            'gradient-4',
            'gradient-5',
            'gradient-6',
            'gradient-7',
            'gradient-8',
            'gradient-9',
          ],
        },
      ],
    },
  },
});

export const cn = (...classes: ClassValue[]) => twMerge(clsx(...classes));
